export default {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    GET_MY_PROFILE: 'GET_MY_PROFILE',
    GET_MY_PROFILE_SUCCESS: 'GET_MY_PROFILE_SUCCESS',
    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS'
}